# -*- coding: utf-8 -*-
"""Gold_Train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tgDus6Ce79KcG826GkCeVvAIEfiydlt2
"""

pip install tensorflow

import pandas as pd
import numpy as np
import joblib

from sklearn.preprocessing import MinMaxScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

# Load Dataset

df = pd.read_csv("/content/goldprices.csv")
df.head()

df.info()

df.describe()

df.columns

# Convert Date column
df["Date"] = pd.to_datetime(df["Date"])

# Sort by date
df = df.sort_values("Date")

df.isnull().sum()

df = df.dropna()

# Keep only Close column
data = df[["Close"]]

# Scale Data

scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(data)

joblib.dump(scaler, "scaler.pkl")

# Create Sequences

time_step = 30

x = []
y = []

for i in range(time_step, len(scaled_data)):
    x.append(scaled_data[i-time_step:i])
    y.append(scaled_data[i])

x = np.array(x)
y = np.array(y)

# Train-Test Split
# ==========================

train_size = int(len(x) * 0.8)

x_train = x[:train_size]
x_test = x[train_size:]

y_train = y[:train_size]
y_test = y[train_size:]

print("Training Shape :", x_train.shape)
print("Testing Shape  :", x_test.shape)

# Build LSTM Model

model = Sequential()

model.add(LSTM(64, return_sequences=True,
               input_shape=(x_train.shape[1], 1)))

model.add(Dropout(0.2))

model.add(LSTM(32))

model.add(Dropout(0.2))

model.add(Dense(16, activation="relu"))

model.add(Dense(1))

model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

model.summary()

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

history = model.fit(
    x_train,
    y_train,
    epochs=30,
    batch_size=32,
    validation_data=(x_test, y_test),
    callbacks=[early_stop]
)

# Save Model

model.save("gold_price_lstm.keras")

print("Model Saved Successfully!")

